# Generated by Django 5.1.1 on 2024-10-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1000)),
                ("content", models.TextField()),
                ("author_writer", models.CharField(max_length=500)),
            ],
        ),
    ]
